### ISSUE TITLE
License is unspecified

### ISSUE THREAD

**Issue by tacosundae** [SevereOverfl0w/krei.alpha#2]
I would love to use this, but there is no indication of licensing terms in this project.

**Comment by SevereOverfl0w** [comment]
You're right, this is on my to-do. I'm going to license as MIT.

On June 26, 2018 5:37:57 PM GMT+01:00, Brian Hollis <notifications@github.com> wrote:
>I would love to use this, but there is no indication of licensing terms
>in this project. 
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/SevereOverfl0w/krei.alpha/issues/2

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
